wandb_version: 1

mlagents_run_id:
  desc: null
  value: HumanAvoidance_wandb_v14
trainer_config:
  desc: null
  value: config/human_avoidance_ppo.yaml
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.6
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1788499080.0
    t:
      1:
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 5
      - 7
      - 13
      - 14
      - 16
      - 23
      - 62
      4: 3.10.9
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
    framework: torch
    m:
    - 1: trainer/step
      6:
      - 3
    - 1: episode/index
      6:
      - 3
mlagents/HumanAvoidance:
  desc: null
  value:
    threaded: false
    init_path: null
    max_steps: 3000000
    self_play: null
    summary_freq: 500
    time_horizon: 128
    trainer_type: ppo
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1
        network_settings:
          memory: null
          normalize: false
          num_layers: 2
          hidden_units: 128
          deterministic: false
          vis_encode_type: simple
          goal_conditioning_type: hyper
    hyperparameters:
      beta: 0.005
      lambd: 0.95
      epsilon: 0.2
      num_epoch: 3
      batch_size: 512
      buffer_size: 10240
      beta_schedule: linear
      learning_rate: 0.0003
      shared_critic: false
      epsilon_schedule: linear
      learning_rate_schedule: linear
    even_checkpoints: false
    keep_checkpoints: 5
    network_settings:
      memory: null
      normalize: true
      num_layers: 2
      hidden_units: 256
      deterministic: false
      vis_encode_type: simple
      goal_conditioning_type: hyper
    behavioral_cloning: null
    checkpoint_interval: 250000
