wandb_version: 1

mlagents_run_id:
  desc: null
  value: HumanAvoidance_wandb_v1
trainer_config:
  desc: null
  value: .\config\human_avoidance_ppo.yaml
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1788336768.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 14
      - 16
      - 23
      - 35
      4: 3.10.9
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
